
// Testing request all contacts
GET http://localhost:4000/students
###

// Testing request single contact
GET http://localhost:4000/student/644fd7e8fe2df9ce30c994f4
###

// Testing request create new contact
POST http://localhost:4000/new-student
content-type: application/json

{
    "firstName": "Andres",
    "lastName": "Martinez",
    "age": "20",
    "phone": "456123789",
    "email": "pepiamila@camila.com",
    "address": "C/c n2",
    "degree": "Machanic",
    "university": "BYU IDAHO"
}
###

// Testing request update contact
PUT http://localhost:4000/update-student/644ff3efd4188ed577cda91e
content-type: application/json

{
    "firstName": "Andres ",
    "lastName": "Pendejo",
    "age": "20",
    "phone": "456123789",
    "email": "andres@andres2.com",
    "address": "C/c n2",
    "degree": "PSYCHOLOGY",
    "university": "BYU IDAHO"
}
###

// Testing request update contact
DELETE http://localhost:4000/delete-student/644ff3efd4188ed577cda91e




